name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]
    env:
      DATABASE_URL: ${{ secrets.TEST_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./Dashboard/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage

      - name: Run coverage and enforce threshold
        working-directory: ./Dashboard/backend/
        run: coverage run --source=./src,. -m pytest && coverage report -m --fail-under=70 -i

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: ./Dashboard/backend/coverage.svg
          working-directory: ./Dashboard/backend/

      - name: Commit coverage badge
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update coverage badge
          file_pattern: ./Dashboard/backend/coverage.svg
